### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by gabn88**
I had issues with my django installation and django-colorful, because 'django' existed, but not 'django.jQuery', which is used. This is a simple fix.

### CODE REVIEW

**Comment by charettes** [comment]
The fixes are not correct, you can't test for sub property existence this way in JS.

`'django' in window && django.jQuery` should do.

**Comment by gabn88** [comment]
Oh, but why does it work on my installation? Before I was getting the "TypeError: $ is not defined' error and now it is working. I assume it always fails and now uses the defined jQuery as default? Sorry for my bad fix, I'm not a good Javascript developer (yet)!

**Comment by charettes** [comment]
It works on your installation because `'django.jQuery' in window` is always false.

**Comment by charettes** [comment]
Discussion moved to #19.

**Pull request closed without merging**
