### PR TITLE
Support Django 3.2

### PR DESCRIPTION
**Pull request by allanlewis**
This PR updates the tox and Travis configs to test against all supported Python and Django versions.

### CODE REVIEW

**Comment by allanlewis** [comment]
This repo's travis config needs updating: https://docs.travis-ci.com/user/migrate/open-source-repository-migration
I'm testing this branch on my fork: allanlewis/django-colorful#1

**Comment by charettes** [comment]
Looks like tests passed on your branch, any idea why they didn't run on this one?

**Comment by charettes** [comment]
nvm, figured out I needed to sign up for the beta and migrate repos.

**Comment by charettes** [comment]
Could you possibly push another commit to see if CI is properly set now. Maybe just amend your latest one and force push?

**Comment by allanlewis** [comment]
Done - I think you might need to select a "plan" in Travis.

**Comment by charettes** [comment]
Looks like we're good, thanks for the adjustments.

**Comment by allanlewis** [comment]
Thanks for the quick response!

**Pull request merged**
